# Generated by Django 2.1.2 on 2018-10-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='started',
            new_name='starter',
        ),
    ]
